### ISSUE TITLE
Nebraska doesn't download packages locally

### ISSUE THREAD

**Issue by qschweitzer** [flatcar/nebraska#1019]
Hi,

We finished to install Nebraska last day.
We have configured it to download packages locally, the idea is that only the Nebraska server have to access flatcar updates by external network. All instances are connected to Nebraska only in internal networks.

But, it doesn't seem to work. I've tested it with a new instance deployment in an older version.
I saw the instance update process in Nebraska vut no package have been downloaded on Neb server.

Nebraska is running himself on Flatcar with podman on a rootless account.
All is deployed with OpenTofu and Ansible.
/updates is 777 (I didn't find solution to have RW access with 774...PUID/GUID issue I think. No SELinux entries in logs about that folder (same on host)).

Our compose file:

  ```
server:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "3010:8000"
    restart: always
    volumes:
      - /updates:/updates
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NEBRASKA_DB_URL=postgres://nebraska:fakepassword@postgres:5432/nebraska?sslmode=disable&connect_timeout=10
    command: sh -c "/nebraska/nebraska -debug -http-log --auth-mode=noop --http-static-dir=/nebraska/static --api-endpoint-suffix=/" -enable-syncer=true -host-flatcar-packages=true -flatcar-packages-path=/updates -nebraska-url=http://nebraska.ourdomain.lan
```

Many thanks,
Bye
